//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub use super::buddies::Entity as Buddies;
pub use super::movies::Entity as Movies;
pub use super::ratings::Entity as Ratings;
pub use super::users::Entity as Users;
